# Generated by Django 3.2 on 2021-05-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_de_barras', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nome_do_produto', models.CharField(max_length=255)),
                ('lote', models.CharField(max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('dt_fabricacao', models.DateField()),
                ('dt_validade', models.DateField()),
                ('pratileira', models.IntegerField()),
                ('codigo_de_barras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
    ]
