# Generated by Django 3.2.1 on 2021-05-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='dt_fabricacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
